

services:
  postgres:
    image: postgres:16-alpine
    container_name: weather_pipeline_db
    environment:
      POSTGRES_USER: pipeline_user
      POSTGRES_PASSWORD: pipeline_pass
      POSTGRES_DB: weather_data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pipeline_user -d weather_data"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: